### ISSUE TITLE
Plot table.txt fails in mumax3.10 on Ubuntu 18.04

### ISSUE THREAD

**Issue by n-s-kiselev** [mumax/3#228]
The plot for table.txt does not work in the web GUI.
The inspection of the webpage element "plot" returns: "Could not load the image".
The issue does not depend on the web browser or version of gnuplot.

**Comment by JeroenMulkers** [comment]
If you run the following command in a terminal, does it return an error message?

`gnuplot -e "set term svg size 480,320 fsize 10" `

**Comment by n-s-kiselev** [comment]
Yes, it does:

```
$ gnuplot -e "set term svg size 480,320 fsize 10"

set term svg size 480,320 fsize 10
                          ^
line 0: unrecognized terminal option
```

**Comment by Dmytro-Apalkov** [comment]
One walkaround is to remove "fsize 10" from function makePlot (in main.go):
`	//cmd := fmt.Sprintf(`set term %v size 400 300; set output "%v.%v";`, term, outf, term)
	cmd := fmt.Sprintf(`set term %v size 400 300 fsize 10; set output "%v.%v";`, term, outf, term)`

Cheers.

**Comment by Dmytro-Apalkov** [comment]
One walk-around is to remove fsize 10 from plot.go:
`	args := []string{"-e", fmt.Sprintf(`set format x "%%g"; set key off; set format y "%%g"; set term svg size 480,320; plot "-" u %v:%v w li; set output;exit;`, a, b)}
	//args := []string{"-e", fmt.Sprintf(`set format x "%%g"; set key off; set format y "%%g"; set term svg size 480,320 fsize 10; plot "-" u %v:%v w li; set output;exit;`, a, b)}`

Cheers.

**Comment by JeroenMulkers** [comment]
@n-s-kiselev  Thank you for filing this bug. 

I could reproduce this bug with gnuplot 5.2. Everything worked fine with gnuplot 4.4 on my machine though. I fixed the bug (see cb63da14) by avoiding the use of the `fsize` keyword which became obsolete somewhere between version 5.0 and 5.2.

If this bugfix does not work for you, feel free to reopen this issue.

**Comment by n-s-kiselev** [comment]
Thank you, Jeroen!
I do confirm that it works with gnuplot v4.4.4 now, but it still fails with gnuplot v5.2.x.

**Comment by JeroenMulkers** [comment]
Strange. On my system it works with gnuplot 4.4.4 before and after the fix, and with gnuplot 5.2.2 and 5.2.6 only after the fix. 

Assuming that you recompiled mumax3 correctly, than the bugs you encounter before and after the fix are system dependent bugs because I am not able to reproduce them.
